### ISSUE TITLE
Fill in condition-specific parameters during parameter mapping

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#103]
Currently this only happens for dynamic parameter overrides.

**Comment by yannikschaelte** [comment]
@dweindl I lost track, what is the status on this?

**Comment by dweindl** [comment]
> @dweindl I lost track, what is the status on this?

Nothing happened here: https://github.com/ICB-DCM/PEtab/blob/develop/petab/parameter_mapping.py#L152
