### ISSUE TITLE
Add automatic creation of visualizationSpecification.tsv for standard plots

### ISSUE THREAD

**Issue by MerktSimon** [ICB-DCM/PEtab#113]

**Comment by paulstapor** [comment]
Would be nice to have the following:
If nothing else is specified, then every experimentId gets an independent plot (as time course, for example) and plots the different observables in different colors

**Comment by paulstapor** [comment]
We basically have that now: A pandas dataframe is created now, according to some simple lists, specified by the used or even completely automated. It's just not saved as a tsv. I would also now argue against saving it, as it's only of temporary use...
