### ISSUE TITLE
Why is there a version 0.0.0a15 on PyPI while master is at 0.0.0a14?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#124]
This should not have happened. There is no 0.0.0a15 tag, github or zenodo release. Skip 0.0.0a15 for next version bump.

**Comment by yannikschaelte** [comment]
Oh, damn. That might have happened when there was this problem with automatic deployment to pypi failing I think.

**Comment by dweindl** [comment]
Ok. Keep in mind (and issue open) for next release.
