### ISSUE TITLE
Checking existance of visualization files should be implemented in PEtab?

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/PEtab#127]
Checking whether visualization files exist for a given model (e.g. benchmark model collection) should be implemented? If so, should an error be thrown or a warning?

**Comment by yannikschaelte** [comment]
I think @paulstapor is working on self-creating in petab some default version of the visualization file which covers some basic setup, thus a visualization file is not always mandatory -- it's an optional file.

**Comment by elbaraim** [comment]
being optional, should be still implemented a warning message?

**Comment by paulstapor** [comment]
There is already something implemented on develop

**Comment by paulstapor** [comment]
The point is: If you do not have a visualization file, you can specify a list of lists, which either groups simulation conditions or observables to one plot
You can also just run a very simple function which plots every observable in one widow

**Comment by paulstapor** [comment]
This is shown in the documentation example (doc/example/example_visualization.ipynb).
Please look into this first ;)

**Comment by paulstapor** [comment]
The last, very high-level function for plotting per observable (plot_measurements_by_observable, here: [https://github.com/ICB-DCM/PEtab/blob/develop/petab/visualize/plot_data_and_simulation.py](https://github.com/ICB-DCM/PEtab/blob/develop/petab/visualize/plot_data_and_simulation.py) )
has not yet an example. If you want, you can add that

**Comment by JanHasenauer** [comment]
I really like the functionality.

Regarding the plotting per observable: There is the issue that scaling and noise parameters might differ. Does this compute the un-scaled, un-offsetted, ... observable?
(If the observatuon function is rather complex, this might not be possible.)

Maybe also sub-divide in cases with identical observation parameters?

**Comment by paulstapor** [comment]
As far as I understand it, it should plot the data based on what is specified in the visualization sheet, i.e.:
 * if there is an observable scale specified, the scaled observable will be plotted
 * if there is an offset specified, the offsetted variable will be plotted.
The observable functions which are specified in the SBML-file however never enter in here...

**Comment by paulstapor** [comment]
Is this issue still open then, i.e., is there something left to work on?

**Comment by yannikschaelte** [comment]
fixed via #126 unless @paulstapor thinks otherwise
