### ISSUE TITLE
Ignore empty space after a name

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/PEtab#13]
For example:
in the measurement data file I have the name 'IR1_P ' and in the SBML model I have 'IR1_P'. It would be good to be able to automatically ignore spaces at the end of the string.

- to avoid:
Unknown observables in measurement file: {'observable_IR1_P '}

**Comment by dweindl** [comment]
Let's not ignore that. They should be corrected in the input data.

**Comment by elbaraim** [comment]
- Do we decide to finally ignore this?
- As an alternative one can add an error specification on empty spaces present in the names?

**Comment by dweindl** [comment]
I'd consider it an error.
