### ISSUE TITLE
Multiple models in publication

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PEtab#132]
@LeonardSchmiester @PhilippStaedter please add details.

We should discuss what to do when we have multiple models in one publication. Say all use the same data and experimental conditions. So the models describe the same stuff, but maybe in more or less detail or alternative networks.

One could put all such models in the same folder and just enumerate / make the names unique. Alternative suggestions?

**Comment by dweindl** [comment]
I don't consider that a PEtab issue. This should be discussed in https://github.com/LoosC/Benchmark-Models/issues.

**Comment by yannikschaelte** [comment]
Eventually becomes a petab issue when we have to write functionality for multiple models (but the overead in petab might actually be pretty low, if we just consider each file separately).

**Comment by dweindl** [comment]
That is a different problem in my opinion. For having a parameter estimation problem based on multiple models,  see #49. But whether different models from any publication should be considered one or multiple problems has nothing to do with PEtab.

**Comment by yannikschaelte** [comment]
closed in favor of https://github.com/LoosC/Benchmark-Models/issues/70
