### ISSUE TITLE
Fix visualization w/o condition names

### ISSUE THREAD

**Issue by MerktSimon** [ICB-DCM/PEtab#142]
https://github.com/ICB-DCM/PEtab/blob/367a0d1d893b30ec6d16d91122a148c96034d782/petab/visualize/helper_functions.py#L168

In the PEtab format the column "conditionName" is optional.  If one chooses to leave this (empty) and does not us a visualization specification file, an "AttributeError: 'DataFrame' object has no attribute 'conditionName'" rises.

**Comment by yannikschaelte** [comment]
@paulstapor I think if the condition name does not exist, we should use a default "Condition n", ok? @MerktSimon to implement this, one could either define a function which "normalizes" the input in the first function called by the user, i.e. adds default values/columns for missing values. Or, whenever needed, you check whether the non-mandatory column exists before using it.

**Comment by JanHasenauer** [comment]
What about using the conditionID? This would provide a unique identifier.

**Comment by yannikschaelte** [comment]
Right. Also, a good thing in general would be to, if a name is needed but none exists, then take the id instead (that has to exist always? if not, and it does not exist, then resort to some generic "Condition n").

**Comment by JanHasenauer** [comment]
The ID has to exist for the mapping. We should enforce this and return an error message otherwise.

**Comment by MerktSimon** [comment]
It already does return a `KeyError: 'Condition table missing mandatory field 'conditionId'` if a conditionId does not exist.
The part of code mentioned above is intended to `# create nicer legend entries from condition names instead of IDs`
So I guess the question is if "Condition n" is in general that much easier on the eye than the conditionID. (Or a way to prevent legends blowing up due to lengthy Ids?)

**Comment by yannikschaelte** [comment]
No, I would not prevent anything from popping up, and just use the id. If the user is not happy, they will have to provide names, imho.

**Comment by paulstapor** [comment]
> No, I would not prevent anything from popping up, and just use the id. If the user is not happy, they will have to provide names, imho.

Agree with it.
ConditionIDs must exist. If names are not present, IDs are the most reasonable default here. I would rather not try to make up something else...
