### ISSUE TITLE
Perelson transformation overflow issue 

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/PEtab#146]
i've encountered an issue with transforming the measurement data of `Perelson_Science1996`. There in the measurement file `measurementData_Perelson_Science1996.tsv` The data is indicated as being `log10` transformed, however, there is a math range issue with `pow(10, 3208000)`.  

it would be good to check this

**Comment by dweindl** [comment]
`observableTransformation=log10` is meant to indicate that we will take log10 of model and data in the objective function. We will try to clarify that in the documentation.

**Comment by dweindl** [comment]
When #154 is resolved, we need to re-check all models.

**Comment by dweindl** [comment]
Measurement file should be fine. See comment above. Now more clearly formulated in the [PEtab documentation](https://petab.readthedocs.io/en/latest/documentation_data_format.html#detailed-field-description). Closing.
