### ISSUE TITLE
Clarify meaning of observableTransformation and parameterScale

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#154]
For these two cases it's somewhat confusing whether they indicate what has been or what should be applied to measurements and parameters.

Most recent discussion was that it might be easiest to go for specifying everything on linear scale.

I.e. for the parameters table, the specified nominalValue and bounds would be transformed according to parameterScale.

Any other thoughts?

**Comment by LeonardSchmiester** [comment]
> Most recent discussion was that it might be easiest to go for specifying everything on linear scale.

Sounds reasonable to me.

**Comment by yannikschaelte** [comment]
one remark: this might lead to numeric problems when values are log-transformed. e.g. 8 in log10 domain is 100000000 in lin domain, and then there could be rounding problems. second, this might also convey a wrong picture. namely if a parameter was optimized in log domain to be -10.532 with an accuracy (step size/whatever) of 1e-3, then in lin space this would look like 0.0.......xzy with a very high precision.

**Comment by elbaraim** [comment]
I think in publications normally the linear parameter value is listed. The approach proposed for the parameter table sounds good to me too. Regarding Yannik's point: e.g. in the model by Fujita et al. (2010), they present the parameter tables in linear scale and there are listed values such as `5.17940x10^(-15)` ... so that would be possible :wink: 

Regarding the `observableTransformation` I think we can keep it as it is, just providing a clearer explanation would be fine?

**Comment by LeonardSchmiester** [comment]
Agreed with your first point. At the moment we usually manually transformed parameter to log scale.

I would prefer to have it consistent between `observableTransformation` and `parameterScale` and therefore write the values always in linear scale.

**Comment by elbaraim** [comment]
That means in the `simulatedData` file the simulated values for the observables should be always printed/saved in linear scale?

**Comment by LeonardSchmiester** [comment]
Yes would probably be the best then

**Comment by fbergmann** [comment]
I'm just looking to update the converter to the models in the new format, and stumbled upon this issue. What is the `parameterScale` column now useful for, when the actual values are now always supposed to be specified in `lin` scale?

**Comment by dweindl** [comment]
This is relevant only for parameter estimation, not for an individual simulation. It showed that optimization is more efficient in log-space (e.g. https://academic.oup.com/bioinformatics/article/35/5/830/5078478), so this field allows you to choose whether you want to scale your parameters for optimization.

**Comment by fbergmann** [comment]
True, but it should say that then in the description of the `parameterScale` element, what it currently says is: 

```
parameterScale [lin|log|log10]

Scale of the parameter. The parameters and boundaries and the nominal parameter value in the following fields are expected to be given in this scale.
```

which is directly contradicted by: 

```
lowerBound [NUMERIC]

Lower bound of the parameter used for optimization. Optional, if estimate==0. Must be provided in linear space, independent of parameterScale.
```

**Comment by dweindl** [comment]
Thanks for pointing out. Missed that during the last update.
