### ISSUE TITLE
documentation: visualizing results using petab.visualize

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/PEtab#162]
as discussed over in the [pyPESTO](https://github.com/ICB-DCM/pyPESTO/issues/200) repo, i'm trying to visualize results obtained by pyPESTO. @yannikschaelte  commented, that i should be using the `plot_data_and_simulation` function you provide with PEtab. It would be nice if that function would take just a petab problem + a data simulation data (frame) in the same format. As that would be exactly the information I have. 

but according to the information i should be able to get some result plotted using

![](https://cl.ly/0ff6e0d18b76/Image%202019-12-02%20at%204.01.50%20PM.png)

data is attached.

[data.tsv.txt](https://github.com/ICB-DCM/PEtab/files/3911975/data.tsv.txt)
[cond.tsv.txt](https://github.com/ICB-DCM/PEtab/files/3911976/cond.tsv.txt)

**Comment by yannikschaelte** [comment]
it should be possible to pass both ``data_file_path`` (for the data) and ``simulation_file_path`` (for the simulations). not sure if that changes sth ...

**Comment by erikadudki** [comment]
I think the issue here is, that the 'observableParameters' column in the data-file is empty. I ran into the same issue recently. 
This has to be added into the PEtab visualization functionality, that an empty 'observableParameters' column is allowed. 
I'm working on it at the moment. 
Thanks for pointing that out!

**Comment by erikadudki** [comment]
@fbergmann now it should work, could you try it again?

**Comment by fbergmann** [comment]
@erikadudki it took a while to check, as it did not work immidiately. When i just reran the lines from the screenshot above, i still got an empty plot with the warning: 

`UserWarning: DatasetIds would have been available, but other grouping was requested. Consider using datasetId.`

This does make it a bit harder, as most petab files come without a datasetId, and i'd have to generate it in many cases. So it would have been nice if `observable_id_list` would have worked. But i used `datasetId` and added the simulation data (here it would have been nice if petab would accepd the `measurement` column, if no `simulatedData` column would be present). And with that i got this plot: 

![](https://cl.ly/a5a21a51f973/Image%202019-12-05%20at%2010.33.41%20AM.png)

This is what i wanted, however I would change the behavior in the drawing, such that the measurement data uses a **dashed** line and the simulationData a **solid** line.

**Comment by LeonardSchmiester** [comment]
> This is what i wanted, however I would change the behavior in the drawing, such that the measurement data uses a dashed line and the simulationData a solid line.

See also #152
