### ISSUE TITLE
Document objective function

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#168]
We didn't specify anywhere what cost function should be used for parameter estimation or how the error model or priors are to be used. Do we want to clarify that or is that left to the user/tool?

**Comment by yannikschaelte** [comment]
Isn't the objective function sufficiently encoded by the measurementFile.noiseDistribution? Gives rise to likelihood, non-trivial priors directly induce a Bayesian posterior.

**Comment by dweindl** [comment]
If it's obvious enough, okay. Thought it might be good to write it out somewhere.

**Comment by dweindl** [comment]
Closing, as apparently not necessary.
