### ISSUE TITLE
Specify format for priors in parameter table

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#17]

**Comment by dweindl** [comment]
If I remember correctly, the result of the last discussion with @yannikschaelte was using `priorDistribution` and `priorParameters` in the parameter table.

priorDistribution := uniform | normal | lognormal
priorParameters := min;max | mean;sd | mean;sd

If starting points sampled from prior distribution fall outside parameter bounds, they will be set to the respective bound.

Separate columns for prior for starting point selection and prior for cost function?

TODO: document

**Comment by yannikschaelte** [comment]
1) A problem with the Distribution might be that we also have the parameterScale column. Would the distributions be on the linear or log/log10 scale? Note: The boundaries and nominalValues are already on the e.g. log-scale.

2) How often does it occur that start point selection and cost function priors differ? For the large-scale models yes, to e.g. force start points from a smalle subdomain. But if that is rather the exception, I would just have one prior here, not two, or maybe one optional one (for start point selection).

**Comment by dweindl** [comment]
> A problem with the Distribution might be that we also have the parameterScale column. Would the distributions be on the linear or log/log10 scale? Note: The boundaries and nominalValues are already on the e.g. log-scale.

For consistency, this should also be on the parameterScale. Although I see that this makes it tedious and error-prone to manually change parameterScale. Other opinions?


> How often does it occur that start point selection and cost function priors differ? For the large-scale models yes, to e.g. force start points from a smalle subdomain. But if that is rather the exception, I would just have one prior here, not two, or maybe one optional one (for start point selection).

Can't say. Usage will tell. So you suggest having only priorDistribution/priorType which will be used for both starting point sampling and cost function?

**Comment by yannikschaelte** [comment]
Yes, but if it's a frequent problem or both are usually treated differently, we might prefer to include both.

**Comment by jvanhoefer** [comment]
In today's discussion with Jan, he suggested that the priors should always be specified in _linear_ scale, since otherwise one had to change the priors (possibly type + parameters) when changing the optimizer's scale.

**Comment by dweindl** [comment]
Hi Jakob,
Since you will probably the most active user of this in the near future, can you make a suggestion for an update of the corresponding data format documentation sections?

**Comment by dweindl** [comment]
This is finished, right?

**Comment by jvanhoefer** [comment]
I would say so.
