### ISSUE TITLE
Meaning of species in condition table

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#181]
We allow providing species as columns in the condition table. I think the meaning of that was not completely clear. Does this set the initial concentration/amount, or does this override the dynamics, setting the respective species to have always that concentration?

The former is probably more what one would expect. However, then I am not completely sure how helpful that is, or if we want to just use `InitialAssignment`s instead.

**Comment by yannikschaelte** [comment]
I would agree that the former is more intuitive, otherwise just use constants. The problem addressed would be condition-specific initial concentrations, but that can easily be solved by parameterized InitialAssignments?

Is this feature motivated by a model where we needed that? I don't recall any.

**Comment by dweindl** [comment]
Agreed with @yannikschaelte and @LeonardSchmiester to proceed as follows:

* condition table can contain columns for (global) parameters, species and compartments
* values for parameters override the respective parameter values of the model (no change)
* values for species override initial concentrations/amounts of the model (clarified)
* values for compartments override initial compartment size (new)

**Comment by dweindl** [comment]
Turns out that this requires some more work and thinking on how that should be done in the context of  preequilibration. As there seems to be no real need, this is postponed indefinitely. For now we will only allow for SBML model parameters as condition table column headers.

Therefore: 
- [ ] Update doc
- [ ] Remove sections for handling of species in condition table

**Comment by yannikschaelte** [comment]
One solution would be to exclusively allow preeq or species overrides. then the situation would be clear. if allowing both, one could affect only e.g. the very initial state, but that might be somewhat arbitrary behavior.

**Comment by LeonardSchmiester** [comment]
- Only simulation condition: See Daniels post
- Preequilibration and overwrite some initials: species in condition table overwrites preequlibration.
- Preequilibration without overwrite: Leave empty in condition table

@yannikschaelte Any objections?

**Comment by dweindl** [comment]
@LeonardSchmiester:
- [ ] Update documentation 

@dweindl:
- [ ] Add special handling for compartments when checking condition table
- [ ] .. add test case
- [ ] Ensure NaN is considered valid input
- [ ] .. add test case

**Comment by dweindl** [comment]
Closed with #238
