### ISSUE TITLE
Visualization: plotType replicates bug

### ISSUE THREAD

**Issue by MerktSimon** [ICB-DCM/PEtab#196]
Visualization with plotType `replicate` leads to empty legend after warning `No handles with labels found to put in legend.`

**Comment by MerktSimon** [comment]
also no simulation ploted

**Comment by MerktSimon** [comment]
Also replicates do get one color each right now.
I would say there should be one color per plotId since there is only one legend per plotID.
Any opinions?

**Comment by dweindl** [comment]
I would say that if replicates belong to different experiments, different colors / shapes would be appropriate. If it is only technical replicates with no specific meaning, same color is fine.

**Comment by MerktSimon** [comment]
why did automatic closing not work here?

**Comment by dweindl** [comment]
> why did automatic closing not work here?

Because we (and github) only closes them when merged into the main branch, in this case `master`. For everybody using the stable version, these issues still exist, therefore leave them open.
