### ISSUE TITLE
BarPlots also with simulated data

### ISSUE THREAD

**Issue by MerktSimon** [ICB-DCM/PEtab#210]

**Comment by MerktSimon** [comment]
any opinions on color coding?
Measurement, Simulation pairs could have same color but e.g. simulation with stripes or all measurements could have the same color and simulation an other.

**Comment by yannikschaelte** [comment]
both would make sense I think. depends on how many data, how many conditions etc. having measurement one color, simulation the other would allow to directly see if both match overall. but for that aim also stripes and no stripes would suffice. (assuming the sim-meas pairs are always plotted in direct neighborhood). in addition, one could however also want to have separate colors for different conditions / data groups.

**Comment by MerktSimon** [comment]
so we could make this an option or just fix a number like 5 and say: up to this number there will be different colors and above we will only differ between measurement and simulation.

**Comment by MerktSimon** [comment]
it is now implemented for now with same color for each measurement/simulation pair
