### ISSUE TITLE
Separate versioning of data format and python library

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#212]
As the library will change much more frequently, and as some users may rather be interested in the file format, it would make sense to use independent version numbers. For the data format, I'd use just integers. For the library ideally semantic versioning.

**Comment by yannikschaelte** [comment]
for the library, just continue using the current a.b.c format, not?

**Comment by yannikschaelte** [comment]
is there actually a need for a `petab_version` in the yaml files then? or should it rather be in the petab releasenotes, it is mentioned once a new format version is introduced, and in the yamls, only the format version is mentioned?

**Comment by yannikschaelte** [comment]
done in #231
