### ISSUE TITLE
Handling of large amounts of plots

### ISSUE THREAD

**Issue by MerktSimon** [ICB-DCM/PEtab#213]
Right now there is no really good way to handle visu files with a very large amount of plotIds.
The only option is to split it up in several files.
So two options solving this would be

- allowing plot_simulation_and_data() to take dataframes instead of file directories so the splitting up becomes more easy

- allowing an option  to save subplots as single files

**Comment by dweindl** [comment]
> * allowing plot_simulation_and_data() to take dataframes instead of file directories so the splitting up becomes more easy

See https://github.com/ICB-DCM/PEtab/pull/211

> * allowing an option  to save subplots as single files

Sounds helpful

**Comment by MerktSimon** [comment]
#211 only implemented this for the other files, though.

**Comment by dweindl** [comment]
> #211 only implemented this for the other files, though.

Ah sorry, yes.
