### ISSUE TITLE
Parameter file: Simplify prior specification

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PEtab#218]
Continuation of #17, see also #131, #206.

Currently, there are {priorX}, {initializationPriorX}, {objectivePriorX}, with X = {Type|Parameters}. The sole prior is supposed to simplify the setting when intitialization and objective prior coincide. However, this leads to unclear overwriting. Thus, it seems preferable to only keep initialization and objective, i.e. enforce defining both. While this creates some overhead when both coincide, it makes things clearer and less error-prone.

**Comment by yannikschaelte** [comment]
here is how the new specification would look: https://github.com/ICB-DCM/PEtab/blob/sampling/doc/documentation_data_format.md#detailed-field-description-1

**Comment by yannikschaelte** [comment]
alternatively, one could also drop objective... and only keep priorType and initializationPriorType, with the latter overwriting the priorType etc. when defined.

advantage: simplifies things in the (common) situation that both priors coincide, and no need to change existing stuff
disadvantage: the overwriting might be unintuitive.

**Comment by dweindl** [comment]
I'd prefer explicit labels. Not sure if there are that many examples with priors yet that would have to be changed. Not feeling too strong about it though.

**Comment by yannikschaelte** [comment]
I think most parameter files have empty 'priorType' and 'priorParameters' columns. Not much work to change though. @jvanhoefer you will use this. Any opinions?

**Comment by jvanhoefer** [comment]
I have no strong feelings towards any of the solutions either...

**Comment by yannikschaelte** [comment]
then we go for the explicit initialization+objective one.

**Comment by yannikschaelte** [comment]
fixed in #222
