### ISSUE TITLE
All parameters need to be in parameters sheet

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/PEtab#219]
At the moment all parameters in the SBML model need to be present in the parameters sheet (also the fixed parameters that are not subject to optimization). Might be more convenient to make it optional to define fixed parameters there and otherwise use the values from the SBML model.

Any opinions?

**Comment by yannikschaelte** [comment]
are there any implementation-wise difficulties (e.g. when checking parameter consistency between files)? if not, strongly in favor of not requiring all parameters that are not to estimate to appear in the parameters file. someone might define pi as a parameter ...

**Comment by dweindl** [comment]
yeah, good to reduce redundancy. (they still *may* be present with `estimate=0`)

**Comment by dweindl** [comment]
Actually the current format description does not state that they all need to be present in the parameter table. So I'd rather consider it a validator-bug (my fault, I guess).

Therefore: 
- [ ] need to update `petab.parameters.get_required_parameters_for_parameter_table`
- [ ] maybe explicitly mention in the documentation that SBML model parameters only *need* to be present if they are to be estimated, but *may* be present in any case.
