### ISSUE TITLE
pylint check for unknown variables

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PEtab#226]
flake8 f405 has been disabled to allow star imports, thus this should be checked in pylint.

**Comment by dweindl** [comment]
Configuring pylint via codacy is a pain. 

- [ ] Add configuration file to repository and
- [ ] tell codacy to use it

**Comment by yannikschaelte** [comment]
> Configuring pylint via codacy is a pain.
> 
> * [ ]  Add configuration file to repository and
> * [ ]  tell codacy to use it

been there, seen that

**Comment by dweindl** [comment]
Closed with #233
