### ISSUE TITLE
Deprecate petab.problem.from_folder?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#245]
`petab.problem.from_folder` loads a set of files based on an expected file naming schema. With the yaml files we have now a much more flexible way of grouping the files. Therefore, I'd propose to deprecate `petab.problem.from_folder` and related functions and remove them in some upcoming release.

**Comment by yannikschaelte** [comment]
I agree. from_folder was quite handy as a means to not have to specify all of those file names when importing, thus improving usability. with the yaml files, that problem should be sufficiently addressed.
