### ISSUE TITLE
add experimentId in the documentation

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/PEtab#28]
The experimentId which is used then for the plotting routines is not yet in the documentation. Its included in some of the models already for example Brannmark.

**Comment by dweindl** [comment]
This was included in the example as an optional extension. If we want to document it here, we first need to discuss what it actually means and what it is used for.

**Comment by dweindl** [comment]
Obsolete or optional. Replaced by the visualization table. See documentation. Closing.
