### ISSUE TITLE
# optimization parameter mismatch  # model parameters

### ISSUE THREAD

**Issue by LukasSp** [ICB-DCM/PEtab#36]
Regarding the branch feature_benchmark2 and the new data format:

Example: In the Crauste_CellSystems2017 model the number of model parameters is bigger than the number of optimization parameters stored in the file parameters_Crauste_CellSystems2017.tsv. The reason for that is, that I don't want to estimate in this specific model the noise, but in the model parameters (sbml-file) I have specified the different noise as parameters (noiseParameter1_*). So when I want to calculate the objective function, I get following issue:

INPUT:  `obj, edatas = importer.create_objective()`
ERROR:
```
Traceback (most recent call last):
line 24, in <module>  obj, edatas = importer.create_objective()
line 200, in create_objective mapping_par_opt_to_par_sim=parameter_mapping
line 444, in get_optimization_to_simulation_scale_mapping
    scale = par_opt_scales_from_df[par_opt_ids_from_df.index(val)]
ValueError: 'noiseParameter1_Naive' is not in list
```

**Comment by dweindl** [comment]
Hi Lukas, this is related to #33. I think we did not reach a final agreement on whether all parameters need to be included there or not.

**Comment by dweindl** [comment]
Required parameters clarified in #42 . Closing.
