### ISSUE TITLE
Extend validator to check if all required parameters are present in parameter table

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#43]
See  #42 for what to check.

Should be added to `petab/lint.py`:
> def check_parameter_sheet(problem):

EDIT: Also check that there are no additional parameters

**Comment by elbaraim** [comment]
do we want to also check this with the SBML model? Meaning that all parameters defined in the SBML are present in the parameter sheet?

**Comment by dweindl** [comment]
All besides the ones appearing as column names in the condition table, yes.

**Comment by dweindl** [comment]
Added first part. Check for parameter overrides from measurement table still missing.

**Comment by erikadudki** [comment]
@dweindl has this been addressed sufficiently?

**Comment by dweindl** [comment]
> @dweindl has this been addressed sufficiently?

No, at least not by me or by any commit referencing this issue.
What needs to be checked here is that all parameters introduced in the condition table (as value, not column - i.e. parameter overrides) are present in the parameter table.

**Comment by dweindl** [comment]
See also https://github.com/LeonardSchmiester/Benchmark-Models/issues/4#issuecomment-559496231. This is not sufficiently checked yet
