### ISSUE TITLE
Handle observable and noise parameter mapping (from opt to sim parameters) with missing data

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PEtab#52]
Is it possible that the overrides do not work, and thus names like observableParameter1... remain in the table, for conditions where some data are missing?

This is e.g. the case for the Schwen model.

**Comment by yannikschaelte** [comment]
If so: How to best deal with it? The parameter mappings should not really be of interest in such cases, as they do not influence the result. Would it be possible to before applying the respective mapping check for a given condition an observable is nan for all time points, and then just set the noise and observable parameters to arbitrary values?

**Comment by dweindl** [comment]
By "do not work", you mean whether it should be allowed to not provide overrides? So initially I thought that it would be okay to not override those parameters but to use the value set for this placeholder in the model. However, I think we agreed at some point that it must always be overridden. (This is not yet implemented, and there is a test case which does not conform to that.

Or do you mean a condition where there is no data for the given observable? This should have no effect on the result, right. Would map that parameter to NaN then.

**Comment by yannikschaelte** [comment]
I mean the latter (to the former: yes, I also think that we agreed that overrides are necessary). So, when there are not data for an observable in a condition (e.g. Schwen, I think also multiple others according to simple tests), then we just set potential noise and observable parameters to nan for all time points.

**Comment by dweindl** [comment]
@yannikschaelte : This is implemented now, right. Or anything else planned here?

**Comment by yannikschaelte** [comment]
yes, that's implemented! (And even highly efficiently now, thanks @dweindl ).
