### ISSUE TITLE
Setup auto-deployment on tag

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#53]
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by dweindl** [comment]
Seems like I'm too stupid. @yannikschaelte want to give it a try?

**Comment by yannikschaelte** [comment]
seems to have worked now using ``username`` instead of ``name`` in the .travis deploy section

**Comment by dweindl** [comment]
> seems to have worked now using `username` instead of `name` in the .travis deploy section

For future reference: Not too informative error message was

> HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
