### ISSUE TITLE
assert_no_trailing_whitespace fails for all-nan columns

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#59]
`TypeError: expected string or bytes-like object`

To reproduce: run `petablint` on `Raia_CancerResearch2011`

@elbaraim : Can you please look into that?

**Comment by FFroehlich** [comment]
sounds like a python2/3 issue, add/remove b when reading file

**Comment by dweindl** [comment]
No, it's really only a nan on which re.match fails
