### ISSUE TITLE
Model name needed in pypesto

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/PEtab#76]
In order to create the AMICI folder, PYPESTO needs some model name. This has been removed in the latest version of petab.
* Can a name be somehow extracted, or should the user be forced to create one in PYPESTO? (prefer the former)
* Might be good to store the name as a problem attribute, as some sort of identifier.

**Comment by dweindl** [comment]
You can get model name (SBML model name, not filename) from the libsbml.Model instance. Should do the job. Choosing the directory should probably also include altering the name if the default directory already exists.

**Comment by yannikschaelte** [comment]
ok! should suffice, since it' really only needed for that purpose.
