### ISSUE TITLE
petab.Problem.from_folder does not set problem.name

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PEtab#77]
To reproduce in pypesto:
```
petab_problem = petab.Problem.from_folder(test.petab_util.folder_base +
                                                  "Zheng_PNAS2012");
importer = pypesto.PetabImporter(petab_problem)
```

**Comment by yannikschaelte** [comment]
yes, the problem.model_name was recently deleted. I am currently trying to overcome this in pypesto in https://github.com/ICB-DCM/pyPESTO/tree/fix_petab_amici, by extracting the name differently.

**Comment by yannikschaelte** [comment]
If I remember correctly, reason for deleting was that we want to be able to base a PetabProblem solely on dataframes.

**Comment by dweindl** [comment]
Do we want to add a name to  `petab.Problem` again or can this be closed?

**Comment by yannikschaelte** [comment]
adding a name again would be a different issue, the above describe one should be fixed.
