### ISSUE TITLE
[petabLint] Check parameter file

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#8]
Add checks for 
- [x] Presence of mandatory columns
- [x] Columns contain only valid entries
- [x] parameterId is unique
- Consistency checks such as 
  - [ ] log parameters > 0
  - [x] lowerBound <= upperBound (is `Inf` a valid bound?)
  - ...

**Comment by LeonardSchmiester** [comment]
We assumed -+inf as a valid bound

**Comment by LeonardSchmiester** [comment]
There is no need for a check if log parameters > 0 right?
The values are given in the indicated scale. So negative values are fine.

**Comment by dweindl** [comment]
b30db18077fa551dadade94f27b9b981afd37631
