### ISSUE TITLE
steady state data

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/PEtab#86]
How do I define steady state data? Only have the preequlibration condition, no simulation condition, and fill the time column with 0?

**Comment by LeonardSchmiester** [comment]
I think no preequilibration condition and set the time to "inf"

**Comment by LoosC** [comment]
Is "Inf" then internally replaced by something reasonable? Or is that covered at all already?

**Comment by dweindl** [comment]
> I think no preequilibration condition and set the time to "inf"

Right.

> Is "Inf" then internally replaced by something reasonable? Or is that covered at all already?

Depends on the exact tool used later on.
For AMICI with forward sensitivities you can use infinity, with adjoints it needs to be replaced.
