### ISSUE TITLE
Add support for non-constant parameter overrides in condition table

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PEtab#90]
Need to adapt optimization to simulation parameter mapping (`core.get_optimization_to_simulation_parameter_mapping`). What else?

**Comment by yannikschaelte** [comment]
Probably also account for scale of parameter according to ``core.get_optimization_to_simulation_scale_mapping``?

**Comment by dweindl** [comment]
Good point, thanks. Will only allow overrides with same scale for a start.
